name: gamewala_repairs
description: GameWala Repairs - MVP Flutter app for shop repairs management
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.2
  intl: ^0.19.0
  flutter_sound: ^9.2.13
  permission_handler: ^11.3.1
  path: ^1.9.0
  path_provider: ^2.1.4
  google_sign_in: ^6.2.1

flutter:
  uses-material-design: true
